- name: install catalogue components
  become: yes
  hosts: catalogue
  tasks:
  - name : setup NPM Source
    shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash "

  - name: install nodejs
    yum:
      name: nodejs
      state: installed
  
  - name: check roboshop user exit or not
    command: id roboshop
    register: out
    ignore_errors: yes

  - when: out.rc != 0
    name: create roboshop user
    become: yes
    user:
      name: roboshop

  - name: check /app directory exit or not
    ansible.builtin.stat:
      path: /app
    register: directory
  - name: print the directory stat
    debug:
      msg: "output: {{ directory }}"

  - when: directory.stat.exits == false
    name: create /app directory
    file:
      path: /app
      state: directory


  