- name: install mongodb components
  become: yes
  hosts: mongodb
  tasks:
    - name: copy mongodb repo to yum.repos.d
      copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb
      yum:
        name: mongodb-org
        state: insalled

    - name: start and enable mongodb
      service:
        name: mongod
        state: started
        enabled: yes

    - name: enable remote connection to mongodb
      replace:
        path: /etc/mongod.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0
      
    - name: restart mongodb
      service:
        name: mongod
        state: restarted